#!/bin/bash
# extraction des paramètres de BdD pour SE3-PLA
. /etc/se3/config_o.cache.sh 

param_file="/var/www/se3/includes/param_db.inc.php"
conf_file="/etc/phpldapadmin/config.php"
conf_file_backup="/etc/phpldapadmin/config-origin.php"
echo "<?php 
#Fichier généré pour SE3-PLA

\$dbhost=\"$dbhost\";
\$dbname=\"$dbname\"; 
\$dbuser=\"$dbuser\"; 
\$dbpass=\"$dbpass\"; 
?\>
>" $param_file 

chown www-se3:root $param_file
chmod 750 $param_file

# fichier de configuration de PLA
if [ ! -e "$conf_file_backup" ]; then
	if [ -e $conf_file ]; then
		cp  $conf_file  $conf_file_backup
	fi
fi

cat /etc/phpldapadmin/config-se3.php > $conf_file
chown root:www-data $conf_file
chmod 640 $conf_file

# fichier de configuration apache
if [ -e /etc/apache2/conf.d/phpldapadmin ]; then
	mv /etc/apache2/conf.d/phpldapadmin /etc/apache2se/conf.d/phpldapadmin
fi
/etc/init.d/apache2se restart


