#!/bin/bash
# nettoyage


param_file="/var/www/se3/includes/param_db.inc.php"
conf_file="/etc/phpldapadmin/config.php"
conf_file_backup="/etc/phpldapadmin/config-origin.php"


rm -f $param_file


# fichier de configuration de PLA
if [ -e "$conf_file_backup" ]; then
	mv -f $conf_file_backup $conf_file || true
fi

# rm -f /etc/apache2se/conf.d/phpldapadmin
# Remise en place du fichier dans sont emplacement d'origine
if [ -e /etc/apache2se/conf.d/phpldapadmin ]; then
	mv -f /etc/apache2se/conf.d/phpldapadmin /etc/apache2/conf.d/phpldapadmin
fi

/etc/init.d/apache2se reload
/etc/init.d/apache2 reload
